/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false cloudflare/worker-configuration.d.ts` (hash: 8a7a708b63af678c62171ee5450151c9)
interface __BaseEnv_Env {
	MEDIA_BUCKET: R2Bucket;
	R2_BUCKET: "goldminer-media";
	CORS_ORIGINS: "http://localhost:3000,http://localhost:5173";
	OPENAI_API_KEY: string;
	OPENAI_TRANSCRIPTION_MODEL: string;
	OPENAI_ANALYSIS_MODEL: string;
	OPENAI_SCORING_MODEL: string;
	GOLDMINER_CONTAINER: DurableObjectNamespace<import("./src/index").GoldMinerContainer>;
	GOLDMINER_WORKFLOW: Workflow<Parameters<import("./src/index").GoldMinerWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "GoldMinerContainer";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "R2_BUCKET" | "CORS_ORIGINS" | "OPENAI_API_KEY" | "OPENAI_TRANSCRIPTION_MODEL" | "OPENAI_ANALYSIS_MODEL" | "OPENAI_SCORING_MODEL">> {}
}
